[general]
live_config_reload = true
import = ["dracula.toml"]

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"
